version: '3.0'
services:
  api:
    build: api
    expose:
      - 80
    ports:
      - 8080:80
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
