version: '3.0'
services:
  api:
    build: api
    depends_on:
      - db
    expose:
      - 80
    ports:
      - 8080:80
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'database'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - db:/var/lib/postgresql/data/
volumes:
  db:
